<?xml version="1.0" encoding="utf-8"?>
<ScriptDocument xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://progea.com">
  <bEnableLog>false</bEnableLog>
  <bEnableSysLog>false</bEnableSysLog>
  <breakpoints xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
  <currentStatusTag i:nil="true" />
  <cycleTimeTag i:nil="true" />
  <disableWhenNotUsed>true</disableWhenNotUsed>
  <fastSamplingInterval>500</fastSamplingInterval>
  <forceWritingOnServer>false</forceWritingOnServer>
  <id>00000000-0000-0000-0000-000000000000</id>
  <listVariableUsed xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
    <d2p1:string>General_Spark_VSR01_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR01_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR01_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR01_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR01_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR01_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR02_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR02_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR02_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR02_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR02_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR02_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR03_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR03_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR03_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR03_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR03_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR03_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR04_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR04_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR04_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR04_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR04_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR04_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR05_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR05_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR05_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR05_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR05_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR05_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR06_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR06_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR06_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR06_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR06_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR06_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR07_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR07_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR07_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR07_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR07_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR07_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR08_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR08_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR08_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR08_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR08_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR08_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR09_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR09_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR09_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR09_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR09_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR09_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR10_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR10_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR10_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR10_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR10_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR10_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR11_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR11_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR11_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR11_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR11_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR12_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR12_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR12_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR12_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR12_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR13_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR13_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR13_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR13_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR13_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR14_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR14_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR14_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR14_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR14_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR15_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR15_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR16_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR16_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR17_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR17_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR18_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR18_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR19_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR19_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>General_Spark_VSR20_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR20_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_PumpPressure_Max</d2p1:string>
  </listVariableUsed>
  <maxCleanCount>2</maxCleanCount>
  <nSelLength>0</nSelLength>
  <nSleepTime>500</nSleepTime>
  <nStartSel>24388</nStartSel>
  <publishingInterval>1000</publishingInterval>
  <removeDisabledItemAfterSecs>30</removeDisabledItemAfterSecs>
  <sCode>'#Language "WWB.NET"

Sub Main Handles .Main

'VSR01
    If General_Spark_VSR01_PLCStateVariable = 0 Then
        SPARK_VSR01_SCADA_ChamberPressure_InRange = SPARK_VSR01_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR01_SCADA_ChamberPressure_Min And SPARK_VSR01_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR01_SCADA_ChamberPressure_Max
        SPARK_VSR01_SCADA_ChamberTemp_InRange     = SPARK_VSR01_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR01_SCADA_ChamberTemp_Min     And SPARK_VSR01_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR01_SCADA_ChamberTemp_Max
        SPARK_VSR01_SCADA_CorkTemp_InRange           = SPARK_VSR01_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR01_SCADA_CorkTemp_Min           And SPARK_VSR01_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR01_SCADA_CorkTemp_Max
        SPARK_VSR01_SCADA_PumpPressure_InRange      = SPARK_VSR01_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR01_SCADA_PumpPressure_Min     And SPARK_VSR01_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR01_SCADA_PumpPressure_Max
    Else
         SPARK_VSR01_SCADA_ChamberPressure_InRange = False
         SPARK_VSR01_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR01_SCADA_CorkTemp_InRange           = False
         SPARK_VSR01_SCADA_PumpPressure_InRange      = False
    End If

'VSR02
    If General_Spark_VSR02_PLCStateVariable = 0 Then
        SPARK_VSR02_SCADA_ChamberPressure_InRange = SPARK_VSR02_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR02_SCADA_ChamberPressure_Min And SPARK_VSR02_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR02_SCADA_ChamberPressure_Max
        SPARK_VSR02_SCADA_ChamberTemp_InRange     = SPARK_VSR02_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR02_SCADA_ChamberTemp_Min     And SPARK_VSR02_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR02_SCADA_ChamberTemp_Max
        SPARK_VSR02_SCADA_CorkTemp_InRange           = SPARK_VSR02_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR02_SCADA_CorkTemp_Min           And SPARK_VSR02_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR02_SCADA_CorkTemp_Max
        SPARK_VSR02_SCADA_PumpPressure_InRange      = SPARK_VSR02_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR02_SCADA_PumpPressure_Min     And SPARK_VSR02_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR02_SCADA_PumpPressure_Max
    Else
         SPARK_VSR02_SCADA_ChamberPressure_InRange = False
         SPARK_VSR02_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR02_SCADA_CorkTemp_InRange           = False
         SPARK_VSR02_SCADA_PumpPressure_InRange      = False
    End If

'VSR03
    If General_Spark_VSR03_PLCStateVariable = 0 Then
        SPARK_VSR03_SCADA_ChamberPressure_InRange = SPARK_VSR03_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR03_SCADA_ChamberPressure_Min And SPARK_VSR03_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR03_SCADA_ChamberPressure_Max
        SPARK_VSR03_SCADA_ChamberTemp_InRange     = SPARK_VSR03_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR03_SCADA_ChamberTemp_Min     And SPARK_VSR03_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR03_SCADA_ChamberTemp_Max
        SPARK_VSR03_SCADA_CorkTemp_InRange           = SPARK_VSR03_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR03_SCADA_CorkTemp_Min           And SPARK_VSR03_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR03_SCADA_CorkTemp_Max
        SPARK_VSR03_SCADA_PumpPressure_InRange      = SPARK_VSR03_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR03_SCADA_PumpPressure_Min     And SPARK_VSR03_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR03_SCADA_PumpPressure_Max
    Else
         SPARK_VSR03_SCADA_ChamberPressure_InRange = False
         SPARK_VSR03_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR03_SCADA_CorkTemp_InRange           = False
         SPARK_VSR03_SCADA_PumpPressure_InRange      = False
    End If

'VSR04
    If General_Spark_VSR04_PLCStateVariable = 0 Then
        SPARK_VSR04_SCADA_ChamberPressure_InRange = SPARK_VSR04_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR04_SCADA_ChamberPressure_Min And SPARK_VSR04_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR04_SCADA_ChamberPressure_Max
        SPARK_VSR04_SCADA_ChamberTemp_InRange     = SPARK_VSR04_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR04_SCADA_ChamberTemp_Min     And SPARK_VSR04_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR04_SCADA_ChamberTemp_Max
        SPARK_VSR04_SCADA_CorkTemp_InRange           = SPARK_VSR04_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR04_SCADA_CorkTemp_Min           And SPARK_VSR04_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR04_SCADA_CorkTemp_Max
        SPARK_VSR04_SCADA_PumpPressure_InRange      = SPARK_VSR04_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR04_SCADA_PumpPressure_Min     And SPARK_VSR04_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR04_SCADA_PumpPressure_Max
    Else
         SPARK_VSR04_SCADA_ChamberPressure_InRange = False
         SPARK_VSR04_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR04_SCADA_CorkTemp_InRange           = False
         SPARK_VSR04_SCADA_PumpPressure_InRange      = False
    End If

'VSR05
    If General_Spark_VSR05_PLCStateVariable = 0 Then
        SPARK_VSR05_SCADA_ChamberPressure_InRange = SPARK_VSR05_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR05_SCADA_ChamberPressure_Min And SPARK_VSR05_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR05_SCADA_ChamberPressure_Max
        SPARK_VSR05_SCADA_ChamberTemp_InRange     = SPARK_VSR05_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR05_SCADA_ChamberTemp_Min     And SPARK_VSR05_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR05_SCADA_ChamberTemp_Max
        SPARK_VSR05_SCADA_CorkTemp_InRange           = SPARK_VSR05_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR05_SCADA_CorkTemp_Min           And SPARK_VSR05_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR05_SCADA_CorkTemp_Max
        SPARK_VSR05_SCADA_PumpPressure_InRange      = SPARK_VSR05_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR05_SCADA_PumpPressure_Min     And SPARK_VSR05_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR05_SCADA_PumpPressure_Max
    Else
         SPARK_VSR05_SCADA_ChamberPressure_InRange = False
         SPARK_VSR05_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR05_SCADA_CorkTemp_InRange           = False
         SPARK_VSR05_SCADA_PumpPressure_InRange      = False
    End If

'VSR06
    If General_Spark_VSR06_PLCStateVariable = 0 Then
        SPARK_VSR06_SCADA_ChamberPressure_InRange = SPARK_VSR06_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR06_SCADA_ChamberPressure_Min And SPARK_VSR06_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR06_SCADA_ChamberPressure_Max
        SPARK_VSR06_SCADA_ChamberTemp_InRange     = SPARK_VSR06_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR06_SCADA_ChamberTemp_Min     And SPARK_VSR06_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR06_SCADA_ChamberTemp_Max
        SPARK_VSR06_SCADA_CorkTemp_InRange           = SPARK_VSR06_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR06_SCADA_CorkTemp_Min           And SPARK_VSR06_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR06_SCADA_CorkTemp_Max
        SPARK_VSR06_SCADA_PumpPressure_InRange      = SPARK_VSR06_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR06_SCADA_PumpPressure_Min     And SPARK_VSR06_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR06_SCADA_PumpPressure_Max
    Else
         SPARK_VSR06_SCADA_ChamberPressure_InRange = False
         SPARK_VSR06_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR06_SCADA_CorkTemp_InRange           = False
         SPARK_VSR06_SCADA_PumpPressure_InRange      = False
    End If

'VSR07
    If General_Spark_VSR07_PLCStateVariable = 0 Then
        SPARK_VSR07_SCADA_ChamberPressure_InRange = SPARK_VSR07_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR07_SCADA_ChamberPressure_Min And SPARK_VSR07_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR07_SCADA_ChamberPressure_Max
        SPARK_VSR07_SCADA_ChamberTemp_InRange     = SPARK_VSR07_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR07_SCADA_ChamberTemp_Min     And SPARK_VSR07_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR07_SCADA_ChamberTemp_Max
        SPARK_VSR07_SCADA_CorkTemp_InRange           = SPARK_VSR07_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR07_SCADA_CorkTemp_Min           And SPARK_VSR07_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR07_SCADA_CorkTemp_Max
        SPARK_VSR07_SCADA_PumpPressure_InRange      = SPARK_VSR07_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR07_SCADA_PumpPressure_Min     And SPARK_VSR07_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR07_SCADA_PumpPressure_Max
    Else
         SPARK_VSR07_SCADA_ChamberPressure_InRange = False
         SPARK_VSR07_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR07_SCADA_CorkTemp_InRange           = False
         SPARK_VSR07_SCADA_PumpPressure_InRange      = False
    End If

'VSR08
    If General_Spark_VSR08_PLCStateVariable = 0 Then
        SPARK_VSR08_SCADA_ChamberPressure_InRange = SPARK_VSR08_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR08_SCADA_ChamberPressure_Min And SPARK_VSR08_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR08_SCADA_ChamberPressure_Max
        SPARK_VSR08_SCADA_ChamberTemp_InRange     = SPARK_VSR08_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR08_SCADA_ChamberTemp_Min     And SPARK_VSR08_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR08_SCADA_ChamberTemp_Max
        SPARK_VSR08_SCADA_CorkTemp_InRange           = SPARK_VSR08_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR08_SCADA_CorkTemp_Min           And SPARK_VSR08_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR08_SCADA_CorkTemp_Max
        SPARK_VSR08_SCADA_PumpPressure_InRange      = SPARK_VSR08_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR08_SCADA_PumpPressure_Min     And SPARK_VSR08_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR08_SCADA_PumpPressure_Max
    Else
         SPARK_VSR08_SCADA_ChamberPressure_InRange = False
         SPARK_VSR08_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR08_SCADA_CorkTemp_InRange           = False
         SPARK_VSR08_SCADA_PumpPressure_InRange      = False
    End If

'VSR09
    If General_Spark_VSR09_PLCStateVariable = 0 Then
        SPARK_VSR09_SCADA_ChamberPressure_InRange = SPARK_VSR09_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR09_SCADA_ChamberPressure_Min And SPARK_VSR09_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR09_SCADA_ChamberPressure_Max
        SPARK_VSR09_SCADA_ChamberTemp_InRange     = SPARK_VSR09_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR09_SCADA_ChamberTemp_Min     And SPARK_VSR09_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR09_SCADA_ChamberTemp_Max
        SPARK_VSR09_SCADA_CorkTemp_InRange           = SPARK_VSR09_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR09_SCADA_CorkTemp_Min           And SPARK_VSR09_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR09_SCADA_CorkTemp_Max
        SPARK_VSR09_SCADA_PumpPressure_InRange      = SPARK_VSR09_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR09_SCADA_PumpPressure_Min     And SPARK_VSR09_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR09_SCADA_PumpPressure_Max
    Else
         SPARK_VSR09_SCADA_ChamberPressure_InRange = False
         SPARK_VSR09_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR09_SCADA_CorkTemp_InRange           = False
         SPARK_VSR09_SCADA_PumpPressure_InRange      = False
    End If

'VSR10
    If General_Spark_VSR10_PLCStateVariable = 0 Then
        SPARK_VSR10_SCADA_ChamberPressure_InRange = SPARK_VSR10_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR10_SCADA_ChamberPressure_Min And SPARK_VSR10_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR10_SCADA_ChamberPressure_Max
        SPARK_VSR10_SCADA_ChamberTemp_InRange     = SPARK_VSR10_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR10_SCADA_ChamberTemp_Min     And SPARK_VSR10_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR10_SCADA_ChamberTemp_Max
        SPARK_VSR10_SCADA_CorkTemp_InRange           = SPARK_VSR10_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR10_SCADA_CorkTemp_Min           And SPARK_VSR10_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR10_SCADA_CorkTemp_Max
        SPARK_VSR10_SCADA_PumpPressure_InRange      = SPARK_VSR10_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR10_SCADA_PumpPressure_Min     And SPARK_VSR10_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR10_SCADA_PumpPressure_Max
    Else
         SPARK_VSR10_SCADA_ChamberPressure_InRange = False
         SPARK_VSR10_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR10_SCADA_CorkTemp_InRange           = False
         SPARK_VSR10_SCADA_PumpPressure_InRange      = False
    End If

'VSR11
    If General_Spark_VSR11_PLCStateVariable = 0 Then
        SPARK_VSR11_SCADA_ChamberPressure_InRange = SPARK_VSR11_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR11_SCADA_ChamberPressure_Min And SPARK_VSR11_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR11_SCADA_ChamberPressure_Max
        SPARK_VSR11_SCADA_ChamberTemp_InRange     = SPARK_VSR11_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR11_SCADA_ChamberTemp_Min     And SPARK_VSR11_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR11_SCADA_ChamberTemp_Max
        SPARK_VSR11_SCADA_CorkTemp_InRange           = SPARK_VSR11_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR11_SCADA_CorkTemp_Min           And SPARK_VSR11_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR11_SCADA_CorkTemp_Max
        SPARK_VSR11_SCADA_PumpPressure_InRange      = SPARK_VSR11_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR11_SCADA_PumpPressure_Min     And SPARK_VSR11_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR11_SCADA_PumpPressure_Max
    Else
         SPARK_VSR11_SCADA_ChamberPressure_InRange = False
         SPARK_VSR11_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR11_SCADA_CorkTemp_InRange           = False
         SPARK_VSR11_SCADA_PumpPressure_InRange      = False
    End If

'VSR12
    If General_Spark_VSR12_PLCStateVariable = 0 Then
        SPARK_VSR12_SCADA_ChamberPressure_InRange = SPARK_VSR12_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR12_SCADA_ChamberPressure_Min And SPARK_VSR12_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR12_SCADA_ChamberPressure_Max
        SPARK_VSR12_SCADA_ChamberTemp_InRange     = SPARK_VSR12_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR12_SCADA_ChamberTemp_Min     And SPARK_VSR12_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR12_SCADA_ChamberTemp_Max
        SPARK_VSR12_SCADA_CorkTemp_InRange           = SPARK_VSR12_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR12_SCADA_CorkTemp_Min           And SPARK_VSR12_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR12_SCADA_CorkTemp_Max
        SPARK_VSR12_SCADA_PumpPressure_InRange      = SPARK_VSR12_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR12_SCADA_PumpPressure_Min     And SPARK_VSR12_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR12_SCADA_PumpPressure_Max
    Else
         SPARK_VSR12_SCADA_ChamberPressure_InRange = False
         SPARK_VSR12_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR12_SCADA_CorkTemp_InRange           = False
         SPARK_VSR12_SCADA_PumpPressure_InRange      = False
    End If

'VSR13
    If General_Spark_VSR13_PLCStateVariable = 0 Then
        SPARK_VSR13_SCADA_ChamberPressure_InRange = SPARK_VSR13_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR13_SCADA_ChamberPressure_Min And SPARK_VSR13_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR13_SCADA_ChamberPressure_Max
        SPARK_VSR13_SCADA_ChamberTemp_InRange     = SPARK_VSR13_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR13_SCADA_ChamberTemp_Min     And SPARK_VSR13_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR13_SCADA_ChamberTemp_Max
        SPARK_VSR13_SCADA_CorkTemp_InRange           = SPARK_VSR13_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR13_SCADA_CorkTemp_Min           And SPARK_VSR13_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR13_SCADA_CorkTemp_Max
        SPARK_VSR13_SCADA_PumpPressure_InRange      = SPARK_VSR13_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR13_SCADA_PumpPressure_Min     And SPARK_VSR13_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR13_SCADA_PumpPressure_Max
    Else
         SPARK_VSR13_SCADA_ChamberPressure_InRange = False
         SPARK_VSR13_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR13_SCADA_CorkTemp_InRange           = False
         SPARK_VSR13_SCADA_PumpPressure_InRange      = False
    End If

'VSR14
    If General_Spark_VSR14_PLCStateVariable = 0 Then
        SPARK_VSR14_SCADA_ChamberPressure_InRange = SPARK_VSR14_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR14_SCADA_ChamberPressure_Min And SPARK_VSR14_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR14_SCADA_ChamberPressure_Max
        SPARK_VSR14_SCADA_ChamberTemp_InRange     = SPARK_VSR14_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR14_SCADA_ChamberTemp_Min     And SPARK_VSR14_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR14_SCADA_ChamberTemp_Max
        SPARK_VSR14_SCADA_CorkTemp_InRange           = SPARK_VSR14_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR14_SCADA_CorkTemp_Min           And SPARK_VSR14_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR14_SCADA_CorkTemp_Max
        SPARK_VSR14_SCADA_PumpPressure_InRange      = SPARK_VSR14_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR14_SCADA_PumpPressure_Min     And SPARK_VSR14_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR14_SCADA_PumpPressure_Max
    Else
         SPARK_VSR14_SCADA_ChamberPressure_InRange = False
         SPARK_VSR14_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR14_SCADA_CorkTemp_InRange           = False
         SPARK_VSR14_SCADA_PumpPressure_InRange      = False
    End If

'VSR15
    If General_Spark_VSR15_PLCStateVariable = 0 Then
        SPARK_VSR15_SCADA_ChamberPressure_InRange = SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR15_SCADA_ChamberPressure_Min And SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR15_SCADA_ChamberPressure_Max
        SPARK_VSR15_SCADA_ChamberTemp_InRange     = SPARK_VSR15_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR15_SCADA_ChamberTemp_Min     And SPARK_VSR15_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR15_SCADA_ChamberTemp_Max
        SPARK_VSR15_SCADA_CorkTemp_InRange           = SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR15_SCADA_CorkTemp_Min           And SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR15_SCADA_CorkTemp_Max
        SPARK_VSR15_SCADA_PumpPressure_InRange      = SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR15_SCADA_PumpPressure_Min     And SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR15_SCADA_PumpPressure_Max
    Else
         SPARK_VSR15_SCADA_ChamberPressure_InRange = False
         SPARK_VSR15_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR15_SCADA_CorkTemp_InRange           = False
         SPARK_VSR15_SCADA_PumpPressure_InRange      = False
    End If

'VSR16
    If General_Spark_VSR16_PLCStateVariable = 0 Then
        SPARK_VSR16_SCADA_ChamberPressure_InRange = SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR16_SCADA_ChamberPressure_Min And SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR16_SCADA_ChamberPressure_Max
        SPARK_VSR16_SCADA_ChamberTemp_InRange     = SPARK_VSR16_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR16_SCADA_ChamberTemp_Min     And SPARK_VSR16_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR16_SCADA_ChamberTemp_Max
        SPARK_VSR16_SCADA_CorkTemp_InRange           = SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR16_SCADA_CorkTemp_Min           And SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR16_SCADA_CorkTemp_Max
        SPARK_VSR16_SCADA_PumpPressure_InRange      = SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR16_SCADA_PumpPressure_Min     And SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR16_SCADA_PumpPressure_Max
    Else
         SPARK_VSR16_SCADA_ChamberPressure_InRange = False
         SPARK_VSR16_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR16_SCADA_CorkTemp_InRange           = False
         SPARK_VSR16_SCADA_PumpPressure_InRange      = False
    End If

'VSR17
    If General_Spark_VSR17_PLCStateVariable = 0 Then
        SPARK_VSR17_SCADA_ChamberPressure_InRange = SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR17_SCADA_ChamberPressure_Min And SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR17_SCADA_ChamberPressure_Max
        SPARK_VSR17_SCADA_ChamberTemp_InRange     = SPARK_VSR17_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR17_SCADA_ChamberTemp_Min     And SPARK_VSR17_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR17_SCADA_ChamberTemp_Max
        SPARK_VSR17_SCADA_CorkTemp_InRange           = SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR17_SCADA_CorkTemp_Min           And SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR17_SCADA_CorkTemp_Max
        SPARK_VSR17_SCADA_PumpPressure_InRange      = SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR17_SCADA_PumpPressure_Min     And SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR17_SCADA_PumpPressure_Max
    Else
         SPARK_VSR17_SCADA_ChamberPressure_InRange = False
         SPARK_VSR17_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR17_SCADA_CorkTemp_InRange           = False
         SPARK_VSR17_SCADA_PumpPressure_InRange      = False
    End If

'VSR18
    If General_Spark_VSR18_PLCStateVariable = 0 Then
        SPARK_VSR18_SCADA_ChamberPressure_InRange = SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR18_SCADA_ChamberPressure_Min And SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR18_SCADA_ChamberPressure_Max
        SPARK_VSR18_SCADA_ChamberTemp_InRange     = SPARK_VSR18_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR18_SCADA_ChamberTemp_Min     And SPARK_VSR18_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR18_SCADA_ChamberTemp_Max
        SPARK_VSR18_SCADA_CorkTemp_InRange           = SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR18_SCADA_CorkTemp_Min           And SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR18_SCADA_CorkTemp_Max
        SPARK_VSR18_SCADA_PumpPressure_InRange      = SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR18_SCADA_PumpPressure_Min     And SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR18_SCADA_PumpPressure_Max
    Else
         SPARK_VSR18_SCADA_ChamberPressure_InRange = False
         SPARK_VSR18_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR18_SCADA_CorkTemp_InRange           = False
         SPARK_VSR18_SCADA_PumpPressure_InRange      = False
    End If

'VSR19
    If General_Spark_VSR19_PLCStateVariable = 0 Then
        SPARK_VSR19_SCADA_ChamberPressure_InRange = SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR19_SCADA_ChamberPressure_Min And SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR19_SCADA_ChamberPressure_Max
        SPARK_VSR19_SCADA_ChamberTemp_InRange     = SPARK_VSR19_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR19_SCADA_ChamberTemp_Min     And SPARK_VSR19_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR19_SCADA_ChamberTemp_Max
        SPARK_VSR19_SCADA_CorkTemp_InRange           = SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR19_SCADA_CorkTemp_Min           And SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR19_SCADA_CorkTemp_Max
        SPARK_VSR19_SCADA_PumpPressure_InRange      = SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR19_SCADA_PumpPressure_Min     And SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR19_SCADA_PumpPressure_Max
    Else
         SPARK_VSR19_SCADA_ChamberPressure_InRange = False
         SPARK_VSR19_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR19_SCADA_CorkTemp_InRange           = False
         SPARK_VSR19_SCADA_PumpPressure_InRange      = False
    End If

'VSR20
    If General_Spark_VSR20_PLCStateVariable = 0 Then
        SPARK_VSR20_SCADA_ChamberPressure_InRange = SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR20_SCADA_ChamberPressure_Min And SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR20_SCADA_ChamberPressure_Max
        SPARK_VSR20_SCADA_ChamberTemp_InRange     = SPARK_VSR20_PLC_KTP_Temperat_PV_Camara      &gt; SPARK_VSR20_SCADA_ChamberTemp_Min     And SPARK_VSR20_PLC_KTP_Temperat_PV_Camara      &lt; SPARK_VSR20_SCADA_ChamberTemp_Max
        SPARK_VSR20_SCADA_CorkTemp_InRange           = SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas        &gt; SPARK_VSR20_SCADA_CorkTemp_Min           And SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas       &lt; SPARK_VSR20_SCADA_CorkTemp_Max
        SPARK_VSR20_SCADA_PumpPressure_InRange      = SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR20_SCADA_PumpPressure_Min     And SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR20_SCADA_PumpPressure_Max
    Else
         SPARK_VSR20_SCADA_ChamberPressure_InRange = False
         SPARK_VSR20_SCADA_ChamberTemp_InRange     = False
         SPARK_VSR20_SCADA_CorkTemp_InRange           = False
         SPARK_VSR20_SCADA_PumpPressure_InRange      = False
    End If

End Sub
</sCode>
  <sessionName i:nil="true" />
  <slowSamplingInterval>5000</slowSamplingInterval>
  <stopCommandTimeout>2000</stopCommandTimeout>
  <threadPriority>Normal</threadPriority>
  <useAlwaysSecureConnections>false</useAlwaysSecureConnections>
  <writeTimeout>0</writeTimeout>
</ScriptDocument>