<?xml version="1.0" encoding="utf-8"?>
<ScriptDocument xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://progea.com">
  <bEnableLog>false</bEnableLog>
  <bEnableSysLog>false</bEnableSysLog>
  <breakpoints xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
  <currentStatusTag i:nil="true" />
  <cycleTimeTag i:nil="true" />
  <disableWhenNotUsed>true</disableWhenNotUsed>
  <fastSamplingInterval>500</fastSamplingInterval>
  <forceWritingOnServer>false</forceWritingOnServer>
  <id>00000000-0000-0000-0000-000000000000</id>
  <listVariableUsed xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
    <d2p1:string>SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR15_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR16_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR17_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR18_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR19_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_PumpPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberPressure_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR20_PLC_KTP_Temperat_PV_Camara</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_ChamberTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_Min</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_InRange</d2p1:string>
    <d2p1:string>SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Bombas</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_PumpPressure_Min</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_PumpPressure_Max</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_PumpPressure_InRange</d2p1:string>
  </listVariableUsed>
  <maxCleanCount>2</maxCleanCount>
  <nSelLength>0</nSelLength>
  <nSleepTime>500</nSleepTime>
  <nStartSel>6276</nStartSel>
  <publishingInterval>1000</publishingInterval>
  <removeDisabledItemAfterSecs>30</removeDisabledItemAfterSecs>
  <sCode>'#Language "WWB.NET"

Sub Main Handles .Main

        'SPARK VSR15 Chamber Pressure in range
        If SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR15_SCADA_ChamberPressure_Min Or SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR15_SCADA_ChamberPressure_Max Then
            SPARK_VSR15_SCADA_ChamberPressure_InRange = False
        Else
            SPARK_VSR15_SCADA_ChamberPressure_InRange = True
        End If

        'SPARK VSR15 Chamber Temperature in range
        If SPARK_VSR15_PLC_KTP_Temperat_PV_Camara &lt; SPARK_VSR15_SCADA_ChamberTemp_Min Or SPARK_VSR15_PLC_KTP_Temperat_PV_Camara &gt; SPARK_VSR15_SCADA_ChamberTemp_Max Then
            SPARK_VSR15_SCADA_ChamberTemp_InRange = False
        Else
            SPARK_VSR15_SCADA_ChamberTemp_InRange = True
        End If

        'SPARK VSR15 Cork Temperature in range
        If SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas &lt; SPARK_VSR15_SCADA_CorkTemp_Min Or SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR15_SCADA_CorkTemp_Max Then
            SPARK_VSR15_SCADA_CorkTemp_InRange = False
        Else
            SPARK_VSR15_SCADA_CorkTemp_InRange = True
        End If

        'SPARK VSR15 Pump Pressure in range
        If SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR15_SCADA_PumpPressure_Min Or SPARK_VSR15_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR15_SCADA_PumpPressure_Max Then
            SPARK_VSR15_SCADA_PumpPressure_InRange = False
        Else
            SPARK_VSR15_SCADA_PumpPressure_InRange = True
        End If

'---------------------------------------------------------------------------------------------

        'SPARK VSR16 Chamber Pressure in range
        If SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR16_SCADA_ChamberPressure_Min Or SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR16_SCADA_ChamberPressure_Max Then
            SPARK_VSR16_SCADA_ChamberPressure_InRange = False
        Else
            SPARK_VSR16_SCADA_ChamberPressure_InRange = True
        End If

        'SPARK VSR16 Chamber Temperature in range
        If SPARK_VSR16_PLC_KTP_Temperat_PV_Camara &lt; SPARK_VSR16_SCADA_ChamberTemp_Min Or SPARK_VSR16_PLC_KTP_Temperat_PV_Camara &gt; SPARK_VSR16_SCADA_ChamberTemp_Max Then
            SPARK_VSR16_SCADA_ChamberTemp_InRange = False
        Else
            SPARK_VSR16_SCADA_ChamberTemp_InRange = True
        End If

        'SPARK VSR16 Cork Temperature in range
        If SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas &lt; SPARK_VSR16_SCADA_CorkTemp_Min Or SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR16_SCADA_CorkTemp_Max Then
            SPARK_VSR16_SCADA_CorkTemp_InRange = False
        Else
            SPARK_VSR16_SCADA_CorkTemp_InRange = True
        End If

        'SPARK VSR16 Pump Pressure in range
        If SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR16_SCADA_PumpPressure_Min Or SPARK_VSR16_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR16_SCADA_PumpPressure_Max Then
            SPARK_VSR16_SCADA_PumpPressure_InRange = False
        Else
            SPARK_VSR16_SCADA_PumpPressure_InRange = True
        End If

'---------------------------------------------------------------------------------------------

        'SPARK VSR17 Chamber Pressure in range
        If SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR17_SCADA_ChamberPressure_Min Or SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR17_SCADA_ChamberPressure_Max Then
            SPARK_VSR17_SCADA_ChamberPressure_InRange = False
        Else
            SPARK_VSR17_SCADA_ChamberPressure_InRange = True
        End If

        'SPARK VSR17 Chamber Temperature in range
        If SPARK_VSR17_PLC_KTP_Temperat_PV_Camara &lt; SPARK_VSR17_SCADA_ChamberTemp_Min Or SPARK_VSR17_PLC_KTP_Temperat_PV_Camara &gt; SPARK_VSR17_SCADA_ChamberTemp_Max Then
            SPARK_VSR17_SCADA_ChamberTemp_InRange = False
        Else
            SPARK_VSR17_SCADA_ChamberTemp_InRange = True
        End If

        'SPARK VSR17 Cork Temperature in range
        If SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas &lt; SPARK_VSR17_SCADA_CorkTemp_Min Or SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR17_SCADA_CorkTemp_Max Then
            SPARK_VSR17_SCADA_CorkTemp_InRange = False
        Else
            SPARK_VSR17_SCADA_CorkTemp_InRange = True
        End If

        'SPARK VSR17 Pump Pressure in range
        If SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR17_SCADA_PumpPressure_Min Or SPARK_VSR17_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR17_SCADA_PumpPressure_Max Then
            SPARK_VSR17_SCADA_PumpPressure_InRange = False
        Else
            SPARK_VSR17_SCADA_PumpPressure_InRange = True
        End If

'---------------------------------------------------------------------------------------------

        'SPARK VSR18 Chamber Pressure in range
        If SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR18_SCADA_ChamberPressure_Min Or SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR18_SCADA_ChamberPressure_Max Then
            SPARK_VSR18_SCADA_ChamberPressure_InRange = False
        Else
            SPARK_VSR18_SCADA_ChamberPressure_InRange = True
        End If

        'SPARK VSR18 Chamber Temperature in range
        If SPARK_VSR18_PLC_KTP_Temperat_PV_Camara &lt; SPARK_VSR18_SCADA_ChamberTemp_Min Or SPARK_VSR18_PLC_KTP_Temperat_PV_Camara &gt; SPARK_VSR18_SCADA_ChamberTemp_Max Then
            SPARK_VSR18_SCADA_ChamberTemp_InRange = False
        Else
            SPARK_VSR18_SCADA_ChamberTemp_InRange = True
        End If

        'SPARK VSR18 Cork Temperature in range
        If SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas &lt; SPARK_VSR18_SCADA_CorkTemp_Min Or SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR18_SCADA_CorkTemp_Max Then
            SPARK_VSR18_SCADA_CorkTemp_InRange = False
        Else
            SPARK_VSR18_SCADA_CorkTemp_InRange = True
        End If

        'SPARK VSR18 Pump Pressure in range
        If SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR18_SCADA_PumpPressure_Min Or SPARK_VSR18_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR18_SCADA_PumpPressure_Max Then
            SPARK_VSR18_SCADA_PumpPressure_InRange = False
        Else
            SPARK_VSR18_SCADA_PumpPressure_InRange = True
        End If

'---------------------------------------------------------------------------------------------

        'SPARK VSR19 Chamber Pressure in range
        If SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR19_SCADA_ChamberPressure_Min Or SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR19_SCADA_ChamberPressure_Max Then
            SPARK_VSR19_SCADA_ChamberPressure_InRange = False
        Else
            SPARK_VSR19_SCADA_ChamberPressure_InRange = True
        End If

        'SPARK VSR19 Chamber Temperature in range
        If SPARK_VSR19_PLC_KTP_Temperat_PV_Camara &lt; SPARK_VSR19_SCADA_ChamberTemp_Min Or SPARK_VSR19_PLC_KTP_Temperat_PV_Camara &gt; SPARK_VSR19_SCADA_ChamberTemp_Max Then
            SPARK_VSR19_SCADA_ChamberTemp_InRange = False
        Else
            SPARK_VSR19_SCADA_ChamberTemp_InRange = True
        End If

        'SPARK VSR19 Cork Temperature in range
        If SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas &lt; SPARK_VSR19_SCADA_CorkTemp_Min Or SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR19_SCADA_CorkTemp_Max Then
            SPARK_VSR19_SCADA_CorkTemp_InRange = False
        Else
            SPARK_VSR19_SCADA_CorkTemp_InRange = True
        End If

        'SPARK VSR19 Pump Pressure in range
        If SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR19_SCADA_PumpPressure_Min Or SPARK_VSR19_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR19_SCADA_PumpPressure_Max Then
            SPARK_VSR19_SCADA_PumpPressure_InRange = False
        Else
            SPARK_VSR19_SCADA_PumpPressure_InRange = True
        End If

'---------------------------------------------------------------------------------------------

        'SPARK VSR20 Chamber Pressure in range
        If SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Camara &lt; SPARK_VSR20_SCADA_ChamberPressure_Min Or SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Camara &gt; SPARK_VSR20_SCADA_ChamberPressure_Max Then
            SPARK_VSR20_SCADA_ChamberPressure_InRange = False
        Else
            SPARK_VSR20_SCADA_ChamberPressure_InRange = True
        End If

        'SPARK VSR20 Chamber Temperature in range
        If SPARK_VSR20_PLC_KTP_Temperat_PV_Camara &lt; SPARK_VSR20_SCADA_ChamberTemp_Min Or SPARK_VSR20_PLC_KTP_Temperat_PV_Camara &gt; SPARK_VSR20_SCADA_ChamberTemp_Max Then
            SPARK_VSR20_SCADA_ChamberTemp_InRange = False
        Else
            SPARK_VSR20_SCADA_ChamberTemp_InRange = True
        End If

        'SPARK VSR20 Cork Temperature in range
        If SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas &lt; SPARK_VSR20_SCADA_CorkTemp_Min Or SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR20_SCADA_CorkTemp_Max Then
            SPARK_VSR20_SCADA_CorkTemp_InRange = False
        Else
            SPARK_VSR20_SCADA_CorkTemp_InRange = True
        End If

        'SPARK VSR20 Pump Pressure in range
        If SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Bombas &lt; SPARK_VSR20_SCADA_PumpPressure_Min Or SPARK_VSR20_PLC_KTP_Movim_PV_mbar_Bombas &gt; SPARK_VSR20_SCADA_PumpPressure_Max Then
            SPARK_VSR20_SCADA_PumpPressure_InRange = False
        Else
            SPARK_VSR20_SCADA_PumpPressure_InRange = True
        End If

End Sub
</sCode>
  <sessionName i:nil="true" />
  <slowSamplingInterval>5000</slowSamplingInterval>
  <stopCommandTimeout>2000</stopCommandTimeout>
  <threadPriority>Normal</threadPriority>
  <useAlwaysSecureConnections>false</useAlwaysSecureConnections>
  <writeTimeout>0</writeTimeout>
</ScriptDocument>