<?xml version="1.0" encoding="utf-8"?>
<ScriptDocument xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://progea.com">
  <bEnableLog>false</bEnableLog>
  <bEnableSysLog>false</bEnableSysLog>
  <breakpoints xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
  <currentStatusTag i:nil="true" />
  <cycleTimeTag i:nil="true" />
  <disableWhenNotUsed>true</disableWhenNotUsed>
  <fastSamplingInterval>500</fastSamplingInterval>
  <forceWritingOnServer>false</forceWritingOnServer>
  <id>00000000-0000-0000-0000-000000000000</id>
  <listVariableUsed xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
    <d2p1:string>SPARK_VSR11_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR11_Status</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_LongDischargeIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_AlarmTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_LongMaxTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_EmailLongDischarge</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_EmailAlarmTempAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_EmailLongMaxTempAbnormality</d2p1:string>
    <d2p1:string>General_Spark_VSR11_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR11_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_sendEmailOfAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR12_Status</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_LongDischargeIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_AlarmTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_LongMaxTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_EmailLongDischarge</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_EmailAlarmTempAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_EmailLongMaxTempAbnormality</d2p1:string>
    <d2p1:string>General_Spark_VSR12_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR12_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_sendEmailOfAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR13_Status</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_LongDischargeIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_AlarmTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_LongMaxTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_EmailLongDischarge</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_EmailAlarmTempAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_EmailLongMaxTempAbnormality</d2p1:string>
    <d2p1:string>General_Spark_VSR13_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR13_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_sendEmailOfAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR14_Status</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_LongDischargeIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_AlarmTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_LongMaxTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_EmailLongDischarge</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_EmailAlarmTempAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_EmailLongMaxTempAbnormality</d2p1:string>
    <d2p1:string>General_Spark_VSR14_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR14_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_sendEmailOfAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR15_Status</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_LongDischargeIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_AlarmTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_LongMaxTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_EmailLongDischarge</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_EmailAlarmTempAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_EmailLongMaxTempAbnormality</d2p1:string>
    <d2p1:string>General_Spark_VSR15_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_sendEmailOfAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR16_Status</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_LongDischargeIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_AlarmTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_LongMaxTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_EmailLongDischarge</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_EmailAlarmTempAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_EmailLongMaxTempAbnormality</d2p1:string>
    <d2p1:string>General_Spark_VSR16_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_sendEmailOfAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR17_Status</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_LongDischargeIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_AlarmTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_LongMaxTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_EmailLongDischarge</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_EmailAlarmTempAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_EmailLongMaxTempAbnormality</d2p1:string>
    <d2p1:string>General_Spark_VSR17_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_sendEmailOfAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR18_Status</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_LongDischargeIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_AlarmTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_LongMaxTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_EmailLongDischarge</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_EmailAlarmTempAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_EmailLongMaxTempAbnormality</d2p1:string>
    <d2p1:string>General_Spark_VSR18_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_sendEmailOfAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR19_Status</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_LongDischargeIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_AlarmTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_LongMaxTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_EmailLongDischarge</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_EmailAlarmTempAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_EmailLongMaxTempAbnormality</d2p1:string>
    <d2p1:string>General_Spark_VSR19_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_sendEmailOfAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR20_Status</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_LongDischargeIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_AlarmTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_LongMaxTempIsAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_EmailLongDischarge</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_EmailAlarmTempAbnormality</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_EmailLongMaxTempAbnormality</d2p1:string>
    <d2p1:string>General_Spark_VSR20_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_sendEmailOfAbnormality</d2p1:string>
  </listVariableUsed>
  <maxCleanCount>2</maxCleanCount>
  <nSelLength>0</nSelLength>
  <nSleepTime>50</nSleepTime>
  <nStartSel>17128</nStartSel>
  <publishingInterval>1000</publishingInterval>
  <removeDisabledItemAfterSecs>30</removeDisabledItemAfterSecs>
  <sCode>'#Language "WWB.NET"

Public Class MachineParameters
    Public machineStatus As Integer
    Public corkTemp_Max_Time As Integer
    Public discharge_Max_Time As Integer
    Public corkTemp_Alarm As Decimal
    Public corkTemp_Max As Decimal
    Public pvCorkTemperature As Decimal
    Public longUnloadIsAbnormality As Boolean
    Public alarmTempIsAbnormality As Boolean
    Public longMaxTempIsAbnormality As Boolean
    Public emailLongUnload As Boolean
    Public emailAlarmTemp As Boolean
    Public emailLongMaxTemp As Boolean
End Class

Public Class Timers
    Public MaxTemperature As Integer
    Public unloading As Integer
End Class

Public Class Commands
    Public bit_abnormalTreatment As Boolean
    Public bit_sendEmail As Boolean
End Class

Sub Main Handles .Main

    Dim Param = New MachineParameters()
    Dim T_min = New Timers()
    Dim results = New Commands()

'VSR11
    T_min.MaxTemperature = SPARK_VSR11_SCADA_MaxTemperatureTimer
    T_min.unloading = SPARK_VSR11_SCADA_unloadingTimer
    Param.machineStatus = SPARK_VSR11_Status
    Param.corkTemp_Max_Time = SPARK_VSR11_SCADA_CorkTemp_Max_Time
    Param.discharge_Max_Time = SPARK_VSR11_SCADA_Discharge_Max_Time
    Param.corkTemp_Alarm = SPARK_VSR11_SCADA_CorkTemp_Alarm
    Param.corkTemp_Max = SPARK_VSR11_SCADA_CorkTemp_Max
    Param.longUnloadIsAbnormality = SPARK_VSR11_SCADA_LongDischargeIsAbnormality
    Param.alarmTempIsAbnormality = SPARK_VSR11_SCADA_AlarmTempIsAbnormality
    Param.longMaxTempIsAbnormality = SPARK_VSR11_SCADA_LongMaxTempIsAbnormality
    Param.emailLongUnload = SPARK_VSR11_SCADA_EmailLongDischarge
    Param.emailAlarmTemp = SPARK_VSR11_SCADA_EmailAlarmTempAbnormality
    Param.emailLongMaxTemp = SPARK_VSR11_SCADA_EmailLongMaxTempAbnormality
    If General_Spark_VSR11_PLCStateVariable = 0 Then
        Try
            Param.pvCorkTemperature = SPARK_VSR11_PLC_KTP_Temperat_PV_Rolhas
        Catch
            Param.pvCorkTemperature = 0
        End Try
    Else
        Param.pvCorkTemperature = 0
    End If

    results = detectAbnormality(Param, T_min)

    SPARK_VSR11_SCADA_MaxTemperatureTimer = T_min.MaxTemperature
    SPARK_VSR11_SCADA_unloadingTimer = T_min.unloading
    SPARK_VSR11_SCADA_abnormalTreatment  = results.bit_abnormalTreatment
    SPARK_VSR11_SCADA_sendEmailOfAbnormality  = results.bit_sendEmail

'VSR12
    T_min.MaxTemperature = SPARK_VSR12_SCADA_MaxTemperatureTimer
    T_min.unloading = SPARK_VSR12_SCADA_unloadingTimer
    Param.machineStatus = SPARK_VSR12_Status
    Param.corkTemp_Max_Time = SPARK_VSR12_SCADA_CorkTemp_Max_Time
    Param.discharge_Max_Time = SPARK_VSR12_SCADA_Discharge_Max_Time
    Param.corkTemp_Alarm = SPARK_VSR12_SCADA_CorkTemp_Alarm
    Param.corkTemp_Max = SPARK_VSR12_SCADA_CorkTemp_Max
    Param.longUnloadIsAbnormality = SPARK_VSR12_SCADA_LongDischargeIsAbnormality
    Param.alarmTempIsAbnormality = SPARK_VSR12_SCADA_AlarmTempIsAbnormality
    Param.longMaxTempIsAbnormality = SPARK_VSR12_SCADA_LongMaxTempIsAbnormality
    Param.emailLongUnload = SPARK_VSR12_SCADA_EmailLongDischarge
    Param.emailAlarmTemp = SPARK_VSR12_SCADA_EmailAlarmTempAbnormality
    Param.emailLongMaxTemp = SPARK_VSR12_SCADA_EmailLongMaxTempAbnormality
    If General_Spark_VSR12_PLCStateVariable = 0 Then
        Try
            Param.pvCorkTemperature = SPARK_VSR12_PLC_KTP_Temperat_PV_Rolhas
        Catch
            Param.pvCorkTemperature = 0
        End Try
    Else
        Param.pvCorkTemperature = 0
    End If

    results = detectAbnormality(Param, T_min)

    SPARK_VSR12_SCADA_MaxTemperatureTimer = T_min.MaxTemperature
    SPARK_VSR12_SCADA_unloadingTimer = T_min.unloading
    SPARK_VSR12_SCADA_abnormalTreatment  = results.bit_abnormalTreatment
    SPARK_VSR12_SCADA_sendEmailOfAbnormality  = results.bit_sendEmail

'VSR13
    T_min.MaxTemperature = SPARK_VSR13_SCADA_MaxTemperatureTimer
    T_min.unloading = SPARK_VSR13_SCADA_unloadingTimer
    Param.machineStatus = SPARK_VSR13_Status
    Param.corkTemp_Max_Time = SPARK_VSR13_SCADA_CorkTemp_Max_Time
    Param.discharge_Max_Time = SPARK_VSR13_SCADA_Discharge_Max_Time
    Param.corkTemp_Alarm = SPARK_VSR13_SCADA_CorkTemp_Alarm
    Param.corkTemp_Max = SPARK_VSR13_SCADA_CorkTemp_Max
    Param.longUnloadIsAbnormality = SPARK_VSR13_SCADA_LongDischargeIsAbnormality
    Param.alarmTempIsAbnormality = SPARK_VSR13_SCADA_AlarmTempIsAbnormality
    Param.longMaxTempIsAbnormality = SPARK_VSR13_SCADA_LongMaxTempIsAbnormality
    Param.emailLongUnload = SPARK_VSR13_SCADA_EmailLongDischarge
    Param.emailAlarmTemp = SPARK_VSR13_SCADA_EmailAlarmTempAbnormality
    Param.emailLongMaxTemp = SPARK_VSR13_SCADA_EmailLongMaxTempAbnormality
    If General_Spark_VSR13_PLCStateVariable = 0 Then
        Try
            Param.pvCorkTemperature = SPARK_VSR13_PLC_KTP_Temperat_PV_Rolhas
        Catch
            Param.pvCorkTemperature = 0
        End Try
    Else
        Param.pvCorkTemperature = 0
    End If

    results = detectAbnormality(Param, T_min)

    SPARK_VSR13_SCADA_MaxTemperatureTimer = T_min.MaxTemperature
    SPARK_VSR13_SCADA_unloadingTimer = T_min.unloading
    SPARK_VSR13_SCADA_abnormalTreatment  = results.bit_abnormalTreatment
    SPARK_VSR13_SCADA_sendEmailOfAbnormality  = results.bit_sendEmail

'VSR14
    T_min.MaxTemperature = SPARK_VSR14_SCADA_MaxTemperatureTimer
    T_min.unloading = SPARK_VSR14_SCADA_unloadingTimer
    Param.machineStatus = SPARK_VSR14_Status
    Param.corkTemp_Max_Time = SPARK_VSR14_SCADA_CorkTemp_Max_Time
    Param.discharge_Max_Time = SPARK_VSR14_SCADA_Discharge_Max_Time
    Param.corkTemp_Alarm = SPARK_VSR14_SCADA_CorkTemp_Alarm
    Param.corkTemp_Max = SPARK_VSR14_SCADA_CorkTemp_Max
    Param.longUnloadIsAbnormality = SPARK_VSR14_SCADA_LongDischargeIsAbnormality
    Param.alarmTempIsAbnormality = SPARK_VSR14_SCADA_AlarmTempIsAbnormality
    Param.longMaxTempIsAbnormality = SPARK_VSR14_SCADA_LongMaxTempIsAbnormality
    Param.emailLongUnload = SPARK_VSR14_SCADA_EmailLongDischarge
    Param.emailAlarmTemp = SPARK_VSR14_SCADA_EmailAlarmTempAbnormality
    Param.emailLongMaxTemp = SPARK_VSR14_SCADA_EmailLongMaxTempAbnormality
    If General_Spark_VSR14_PLCStateVariable = 0 Then
        Try
            Param.pvCorkTemperature = SPARK_VSR14_PLC_KTP_Temperat_PV_Rolhas
        Catch
            Param.pvCorkTemperature = 0
        End Try
    Else
        Param.pvCorkTemperature = 0
    End If

    results = detectAbnormality(Param, T_min)

    SPARK_VSR14_SCADA_MaxTemperatureTimer = T_min.MaxTemperature
    SPARK_VSR14_SCADA_unloadingTimer = T_min.unloading
    SPARK_VSR14_SCADA_abnormalTreatment  = results.bit_abnormalTreatment
    SPARK_VSR14_SCADA_sendEmailOfAbnormality  = results.bit_sendEmail

'VSR15
    T_min.MaxTemperature = SPARK_VSR15_SCADA_MaxTemperatureTimer
    T_min.unloading = SPARK_VSR15_SCADA_unloadingTimer
    Param.machineStatus = SPARK_VSR15_Status
    Param.corkTemp_Max_Time = SPARK_VSR15_SCADA_CorkTemp_Max_Time
    Param.discharge_Max_Time = SPARK_VSR15_SCADA_Discharge_Max_Time
    Param.corkTemp_Alarm = SPARK_VSR15_SCADA_CorkTemp_Alarm
    Param.corkTemp_Max = SPARK_VSR15_SCADA_CorkTemp_Max
    Param.longUnloadIsAbnormality = SPARK_VSR15_SCADA_LongDischargeIsAbnormality
    Param.alarmTempIsAbnormality = SPARK_VSR15_SCADA_AlarmTempIsAbnormality
    Param.longMaxTempIsAbnormality = SPARK_VSR15_SCADA_LongMaxTempIsAbnormality
    Param.emailLongUnload = SPARK_VSR15_SCADA_EmailLongDischarge
    Param.emailAlarmTemp = SPARK_VSR15_SCADA_EmailAlarmTempAbnormality
    Param.emailLongMaxTemp = SPARK_VSR15_SCADA_EmailLongMaxTempAbnormality
    If General_Spark_VSR15_PLCStateVariable = 0 Then
        Try
            Param.pvCorkTemperature = SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas
        Catch
            Param.pvCorkTemperature = 0
        End Try
    Else
        Param.pvCorkTemperature = 0
    End If

    results = detectAbnormality(Param, T_min)

    SPARK_VSR15_SCADA_MaxTemperatureTimer = T_min.MaxTemperature
    SPARK_VSR15_SCADA_unloadingTimer = T_min.unloading
    SPARK_VSR15_SCADA_abnormalTreatment  = results.bit_abnormalTreatment
    SPARK_VSR15_SCADA_sendEmailOfAbnormality  = results.bit_sendEmail

'VSR16
    T_min.MaxTemperature = SPARK_VSR16_SCADA_MaxTemperatureTimer
    T_min.unloading = SPARK_VSR16_SCADA_unloadingTimer
    Param.machineStatus = SPARK_VSR16_Status
    Param.corkTemp_Max_Time = SPARK_VSR16_SCADA_CorkTemp_Max_Time
    Param.discharge_Max_Time = SPARK_VSR16_SCADA_Discharge_Max_Time
    Param.corkTemp_Alarm = SPARK_VSR16_SCADA_CorkTemp_Alarm
    Param.corkTemp_Max = SPARK_VSR16_SCADA_CorkTemp_Max
    Param.longUnloadIsAbnormality = SPARK_VSR16_SCADA_LongDischargeIsAbnormality
    Param.alarmTempIsAbnormality = SPARK_VSR16_SCADA_AlarmTempIsAbnormality
    Param.longMaxTempIsAbnormality = SPARK_VSR16_SCADA_LongMaxTempIsAbnormality
    Param.emailLongUnload = SPARK_VSR16_SCADA_EmailLongDischarge
    Param.emailAlarmTemp = SPARK_VSR16_SCADA_EmailAlarmTempAbnormality
    Param.emailLongMaxTemp = SPARK_VSR16_SCADA_EmailLongMaxTempAbnormality
    If General_Spark_VSR16_PLCStateVariable = 0 Then
        Try
            Param.pvCorkTemperature = SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas
        Catch
            Param.pvCorkTemperature = 0
        End Try
    Else
        Param.pvCorkTemperature = 0
    End If

    results = detectAbnormality(Param, T_min)

    SPARK_VSR16_SCADA_MaxTemperatureTimer = T_min.MaxTemperature
    SPARK_VSR16_SCADA_unloadingTimer = T_min.unloading
    SPARK_VSR16_SCADA_abnormalTreatment  = results.bit_abnormalTreatment
    SPARK_VSR16_SCADA_sendEmailOfAbnormality  = results.bit_sendEmail

'VSR17
    T_min.MaxTemperature = SPARK_VSR17_SCADA_MaxTemperatureTimer
    T_min.unloading = SPARK_VSR17_SCADA_unloadingTimer
    Param.machineStatus = SPARK_VSR17_Status
    Param.corkTemp_Max_Time = SPARK_VSR17_SCADA_CorkTemp_Max_Time
    Param.discharge_Max_Time = SPARK_VSR17_SCADA_Discharge_Max_Time
    Param.corkTemp_Alarm = SPARK_VSR17_SCADA_CorkTemp_Alarm
    Param.corkTemp_Max = SPARK_VSR17_SCADA_CorkTemp_Max
    Param.longUnloadIsAbnormality = SPARK_VSR17_SCADA_LongDischargeIsAbnormality
    Param.alarmTempIsAbnormality = SPARK_VSR17_SCADA_AlarmTempIsAbnormality
    Param.longMaxTempIsAbnormality = SPARK_VSR17_SCADA_LongMaxTempIsAbnormality
    Param.emailLongUnload = SPARK_VSR17_SCADA_EmailLongDischarge
    Param.emailAlarmTemp = SPARK_VSR17_SCADA_EmailAlarmTempAbnormality
    Param.emailLongMaxTemp = SPARK_VSR17_SCADA_EmailLongMaxTempAbnormality
    If General_Spark_VSR17_PLCStateVariable = 0 Then
        Try
            Param.pvCorkTemperature = SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas
        Catch
            Param.pvCorkTemperature = 0
        End Try
    Else
        Param.pvCorkTemperature = 0
    End If

    results = detectAbnormality(Param, T_min)

    SPARK_VSR17_SCADA_MaxTemperatureTimer = T_min.MaxTemperature
    SPARK_VSR17_SCADA_unloadingTimer = T_min.unloading
    SPARK_VSR17_SCADA_abnormalTreatment  = results.bit_abnormalTreatment
    SPARK_VSR17_SCADA_sendEmailOfAbnormality  = results.bit_sendEmail

'VSR18
    T_min.MaxTemperature = SPARK_VSR18_SCADA_MaxTemperatureTimer
    T_min.unloading = SPARK_VSR18_SCADA_unloadingTimer
    Param.machineStatus = SPARK_VSR18_Status
    Param.corkTemp_Max_Time = SPARK_VSR18_SCADA_CorkTemp_Max_Time
    Param.discharge_Max_Time = SPARK_VSR18_SCADA_Discharge_Max_Time
    Param.corkTemp_Alarm = SPARK_VSR18_SCADA_CorkTemp_Alarm
    Param.corkTemp_Max = SPARK_VSR18_SCADA_CorkTemp_Max
    Param.longUnloadIsAbnormality = SPARK_VSR18_SCADA_LongDischargeIsAbnormality
    Param.alarmTempIsAbnormality = SPARK_VSR18_SCADA_AlarmTempIsAbnormality
    Param.longMaxTempIsAbnormality = SPARK_VSR18_SCADA_LongMaxTempIsAbnormality
    Param.emailLongUnload = SPARK_VSR18_SCADA_EmailLongDischarge
    Param.emailAlarmTemp = SPARK_VSR18_SCADA_EmailAlarmTempAbnormality
    Param.emailLongMaxTemp = SPARK_VSR18_SCADA_EmailLongMaxTempAbnormality
    If General_Spark_VSR18_PLCStateVariable = 0 Then
        Try
            Param.pvCorkTemperature = SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas
        Catch
            Param.pvCorkTemperature = 0
        End Try
    Else
        Param.pvCorkTemperature = 0
    End If

    results = detectAbnormality(Param, T_min)

    SPARK_VSR18_SCADA_MaxTemperatureTimer = T_min.MaxTemperature
    SPARK_VSR18_SCADA_unloadingTimer = T_min.unloading
    SPARK_VSR18_SCADA_abnormalTreatment  = results.bit_abnormalTreatment
    SPARK_VSR18_SCADA_sendEmailOfAbnormality  = results.bit_sendEmail

'VSR19
    T_min.MaxTemperature = SPARK_VSR19_SCADA_MaxTemperatureTimer
    T_min.unloading = SPARK_VSR19_SCADA_unloadingTimer
    Param.machineStatus = SPARK_VSR19_Status
    Param.corkTemp_Max_Time = SPARK_VSR19_SCADA_CorkTemp_Max_Time
    Param.discharge_Max_Time = SPARK_VSR19_SCADA_Discharge_Max_Time
    Param.corkTemp_Alarm = SPARK_VSR19_SCADA_CorkTemp_Alarm
    Param.corkTemp_Max = SPARK_VSR19_SCADA_CorkTemp_Max
    Param.longUnloadIsAbnormality = SPARK_VSR19_SCADA_LongDischargeIsAbnormality
    Param.alarmTempIsAbnormality = SPARK_VSR19_SCADA_AlarmTempIsAbnormality
    Param.longMaxTempIsAbnormality = SPARK_VSR19_SCADA_LongMaxTempIsAbnormality
    Param.emailLongUnload = SPARK_VSR19_SCADA_EmailLongDischarge
    Param.emailAlarmTemp = SPARK_VSR19_SCADA_EmailAlarmTempAbnormality
    Param.emailLongMaxTemp = SPARK_VSR19_SCADA_EmailLongMaxTempAbnormality
    If General_Spark_VSR19_PLCStateVariable = 0 Then
        Try
            Param.pvCorkTemperature = SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas
        Catch
            Param.pvCorkTemperature = 0
        End Try
    Else
        Param.pvCorkTemperature = 0
    End If

    results = detectAbnormality(Param, T_min)

    SPARK_VSR19_SCADA_MaxTemperatureTimer = T_min.MaxTemperature
    SPARK_VSR19_SCADA_unloadingTimer = T_min.unloading
    SPARK_VSR19_SCADA_abnormalTreatment  = results.bit_abnormalTreatment
    SPARK_VSR19_SCADA_sendEmailOfAbnormality  = results.bit_sendEmail

'VSR20
    T_min.MaxTemperature = SPARK_VSR20_SCADA_MaxTemperatureTimer
    T_min.unloading = SPARK_VSR20_SCADA_unloadingTimer
    Param.machineStatus = SPARK_VSR20_Status
    Param.corkTemp_Max_Time = SPARK_VSR20_SCADA_CorkTemp_Max_Time
    Param.discharge_Max_Time = SPARK_VSR20_SCADA_Discharge_Max_Time
    Param.corkTemp_Alarm = SPARK_VSR20_SCADA_CorkTemp_Alarm
    Param.corkTemp_Max = SPARK_VSR20_SCADA_CorkTemp_Max
    Param.longUnloadIsAbnormality = SPARK_VSR20_SCADA_LongDischargeIsAbnormality
    Param.alarmTempIsAbnormality = SPARK_VSR20_SCADA_AlarmTempIsAbnormality
    Param.longMaxTempIsAbnormality = SPARK_VSR20_SCADA_LongMaxTempIsAbnormality
    Param.emailLongUnload = SPARK_VSR20_SCADA_EmailLongDischarge
    Param.emailAlarmTemp = SPARK_VSR20_SCADA_EmailAlarmTempAbnormality
    Param.emailLongMaxTemp = SPARK_VSR20_SCADA_EmailLongMaxTempAbnormality
    If General_Spark_VSR20_PLCStateVariable = 0 Then
        Try
            Param.pvCorkTemperature = SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas
        Catch
            Param.pvCorkTemperature = 0
        End Try
    Else
        Param.pvCorkTemperature = 0
    End If

    results = detectAbnormality(Param, T_min)

    SPARK_VSR20_SCADA_MaxTemperatureTimer = T_min.MaxTemperature
    SPARK_VSR20_SCADA_unloadingTimer = T_min.unloading
    SPARK_VSR20_SCADA_abnormalTreatment  = results.bit_abnormalTreatment
    SPARK_VSR20_SCADA_sendEmailOfAbnormality  = results.bit_sendEmail
End Sub

 Function  detectAbnormality(M As MachineParameters, ByRef T As Timers)
    Dim cmd = New Commands()
    Dim bit_longWhileUnloading, bit_AlarmTemperature, bit_longWhileMaxTemperature As Boolean

' Unloading took so long
     If M.machineStatus = 3 Then
        T.unloading = T.unloading+1
    Else
        T.unloading = 0
    End If
   bit_longWhileUnloading = M.discharge_Max_Time&gt;0 And T.unloading &gt;= M.discharge_Max_Time

' Alarm temperature
   bit_AlarmTemperature = M.pvCorkTemperature&gt;= M.corkTemp_Alarm

' Maximume temperature remained so long
    If M.pvCorkTemperature &gt; M.corkTemp_Max Then
        T.MaxTemperature = T.MaxTemperature+1
    Else
        T.MaxTemperature = 0
    End If

   bit_longWhileMaxTemperature = M.corkTemp_Max_Time&gt;0 And T.MaxTemperature&gt;=M.corkTemp_Max_Time

   cmd.bit_abnormalTreatment = (bit_longWhileUnloading And M.longUnloadIsAbnormality) _
                                            Or (bit_AlarmTemperature And M.alarmTempIsAbnormality) _
                                            Or (bit_longWhileMaxTemperature And M.longMaxTempIsAbnormality)

    cmd.bit_sendEmail = (bit_longWhileUnloading And M.emailLongUnload) _
                              Or (bit_AlarmTemperature And M.emailAlarmTemp) _
                              Or (bit_longWhileMaxTemperature And M.emailLongMaxTemp)
   Return cmd
 End Function
</sCode>
  <sessionName i:nil="true" />
  <slowSamplingInterval>5000</slowSamplingInterval>
  <stopCommandTimeout>2000</stopCommandTimeout>
  <threadPriority>Normal</threadPriority>
  <useAlwaysSecureConnections>false</useAlwaysSecureConnections>
  <writeTimeout>0</writeTimeout>
</ScriptDocument>