<?xml version="1.0" encoding="utf-8"?>
<ScriptDocument xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://progea.com">
  <bEnableLog>false</bEnableLog>
  <bEnableSysLog>false</bEnableSysLog>
  <breakpoints xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
  <currentStatusTag i:nil="true" />
  <cycleTimeTag i:nil="true" />
  <disableWhenNotUsed>true</disableWhenNotUsed>
  <fastSamplingInterval>500</fastSamplingInterval>
  <forceWritingOnServer>false</forceWritingOnServer>
  <id>00000000-0000-0000-0000-000000000000</id>
  <listVariableUsed xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
    <d2p1:string>SPARK_VSR11_Status</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>General_Spark_VSR11_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR11_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR11_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR12_Status</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>General_Spark_VSR12_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR12_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR12_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR13_Status</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>General_Spark_VSR13_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR13_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR13_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR14_Status</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>General_Spark_VSR14_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR14_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR14_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR15_Status</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>General_Spark_VSR15_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR15_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR16_Status</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>General_Spark_VSR16_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR16_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR17_Status</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>General_Spark_VSR17_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR17_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR18_Status</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>General_Spark_VSR18_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR18_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR19_Status</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>General_Spark_VSR19_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR19_SCADA_abnormalTreatment</d2p1:string>
    <d2p1:string>SPARK_VSR20_Status</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_unloadingTimer</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_Discharge_Max_Time</d2p1:string>
    <d2p1:string>General_Spark_VSR20_PLCStateVariable</d2p1:string>
    <d2p1:string>SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_Alarm</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_Max</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_MaxTemperatureTimer</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_CorkTemp_Max_Time</d2p1:string>
    <d2p1:string>SPARK_VSR20_SCADA_abnormalTreatment</d2p1:string>
  </listVariableUsed>
  <maxCleanCount>2</maxCleanCount>
  <nSelLength>0</nSelLength>
  <nSleepTime>50</nSleepTime>
  <nStartSel>12949</nStartSel>
  <publishingInterval>1000</publishingInterval>
  <removeDisabledItemAfterSecs>30</removeDisabledItemAfterSecs>
  <sCode>'#Language "WWB.NET"
Sub Main Handles .Main

Dim bit_longWhileUnloading, bit_AlarmTemperature, bit_longWhileMaxTemperature As Boolean

'VSR11
    If SPARK_VSR11_Status = 3 Then
        SPARK_VSR11_SCADA_unloadingTimer = SPARK_VSR11_SCADA_unloadingTimer+1
    Else
            SPARK_VSR11_SCADA_unloadingTimer = 0
    End If
   bit_longWhileUnloading = SPARK_VSR11_SCADA_Discharge_Max_Time&gt;0 And SPARK_VSR11_SCADA_unloadingTimer&gt;SPARK_VSR11_SCADA_Discharge_Max_Time

    If General_Spark_VSR11_PLCStateVariable = 0 Then
        Try
            bit_AlarmTemperature = SPARK_VSR11_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR11_SCADA_CorkTemp_Alarm
        Catch
            Finally
        End Try
    End If

    If General_Spark_VSR11_PLCStateVariable = 0 Then
        Try
            If SPARK_VSR11_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR11_SCADA_CorkTemp_Max Then
                SPARK_VSR11_SCADA_MaxTemperatureTimer = SPARK_VSR11_SCADA_MaxTemperatureTimer+1
            Else
                    SPARK_VSR11_SCADA_MaxTemperatureTimer = 0
            End If
        Catch
            Finally
        End Try
    End If
   bit_longWhileMaxTemperature = SPARK_VSR11_SCADA_CorkTemp_Max_Time&gt;0 And SPARK_VSR11_SCADA_MaxTemperatureTimer&gt;SPARK_VSR11_SCADA_CorkTemp_Max_Time

   SPARK_VSR11_SCADA_abnormalTreatment = bit_longWhileUnloading Or bit_AlarmTemperature Or bit_longWhileMaxTemperature

'VSR12
    If SPARK_VSR12_Status = 3 Then
        SPARK_VSR12_SCADA_unloadingTimer = SPARK_VSR12_SCADA_unloadingTimer+1
    Else
            SPARK_VSR12_SCADA_unloadingTimer = 0
    End If
   bit_longWhileUnloading = SPARK_VSR12_SCADA_Discharge_Max_Time&gt;0 And SPARK_VSR12_SCADA_unloadingTimer&gt;SPARK_VSR12_SCADA_Discharge_Max_Time

    If General_Spark_VSR12_PLCStateVariable = 0 Then
        Try
            bit_AlarmTemperature = SPARK_VSR12_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR12_SCADA_CorkTemp_Alarm
        Catch
            Finally
        End Try
    End If

    If General_Spark_VSR12_PLCStateVariable = 0 Then
        Try
            If SPARK_VSR12_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR12_SCADA_CorkTemp_Max Then
                SPARK_VSR12_SCADA_MaxTemperatureTimer = SPARK_VSR12_SCADA_MaxTemperatureTimer+1
            Else
                    SPARK_VSR12_SCADA_MaxTemperatureTimer = 0
            End If
        Catch
            Finally
        End Try
    End If
   bit_longWhileMaxTemperature = SPARK_VSR12_SCADA_CorkTemp_Max_Time&gt;0 And SPARK_VSR12_SCADA_MaxTemperatureTimer&gt;SPARK_VSR12_SCADA_CorkTemp_Max_Time

   SPARK_VSR12_SCADA_abnormalTreatment = bit_longWhileUnloading Or bit_AlarmTemperature Or bit_longWhileMaxTemperature

'VSR13
    If SPARK_VSR13_Status = 3 Then
        SPARK_VSR13_SCADA_unloadingTimer = SPARK_VSR13_SCADA_unloadingTimer+1
    Else
            SPARK_VSR13_SCADA_unloadingTimer = 0
    End If
   bit_longWhileUnloading = SPARK_VSR13_SCADA_Discharge_Max_Time&gt;0 And SPARK_VSR13_SCADA_unloadingTimer&gt;SPARK_VSR13_SCADA_Discharge_Max_Time

    If General_Spark_VSR13_PLCStateVariable = 0 Then
        Try
            bit_AlarmTemperature = SPARK_VSR13_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR13_SCADA_CorkTemp_Alarm
        Catch
            Finally
        End Try
    End If

    If General_Spark_VSR13_PLCStateVariable = 0 Then
        Try
            If SPARK_VSR13_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR13_SCADA_CorkTemp_Max Then
                SPARK_VSR13_SCADA_MaxTemperatureTimer = SPARK_VSR13_SCADA_MaxTemperatureTimer+1
            Else
                    SPARK_VSR13_SCADA_MaxTemperatureTimer = 0
            End If
        Catch
            Finally
        End Try
    End If
   bit_longWhileMaxTemperature = SPARK_VSR13_SCADA_CorkTemp_Max_Time&gt;0 And SPARK_VSR13_SCADA_MaxTemperatureTimer&gt;SPARK_VSR13_SCADA_CorkTemp_Max_Time

   SPARK_VSR13_SCADA_abnormalTreatment = bit_longWhileUnloading Or bit_AlarmTemperature Or bit_longWhileMaxTemperature

'VSR14
    If SPARK_VSR14_Status = 3 Then
        SPARK_VSR14_SCADA_unloadingTimer = SPARK_VSR14_SCADA_unloadingTimer+1
    Else
            SPARK_VSR14_SCADA_unloadingTimer = 0
    End If
   bit_longWhileUnloading = SPARK_VSR14_SCADA_Discharge_Max_Time&gt;0 And SPARK_VSR14_SCADA_unloadingTimer&gt;SPARK_VSR14_SCADA_Discharge_Max_Time

    If General_Spark_VSR14_PLCStateVariable = 0 Then
        Try
            bit_AlarmTemperature = SPARK_VSR14_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR14_SCADA_CorkTemp_Alarm
        Catch
            Finally
        End Try
    End If

    If General_Spark_VSR14_PLCStateVariable = 0 Then
        Try
            If SPARK_VSR14_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR14_SCADA_CorkTemp_Max Then
                SPARK_VSR14_SCADA_MaxTemperatureTimer = SPARK_VSR14_SCADA_MaxTemperatureTimer+1
            Else
                    SPARK_VSR14_SCADA_MaxTemperatureTimer = 0
            End If
        Catch
            Finally
        End Try
    End If
   bit_longWhileMaxTemperature = SPARK_VSR14_SCADA_CorkTemp_Max_Time&gt;0 And SPARK_VSR14_SCADA_MaxTemperatureTimer&gt;SPARK_VSR14_SCADA_CorkTemp_Max_Time

   SPARK_VSR14_SCADA_abnormalTreatment = bit_longWhileUnloading Or bit_AlarmTemperature Or bit_longWhileMaxTemperature

'VSR15
    If SPARK_VSR15_Status = 3 Then
        SPARK_VSR15_SCADA_unloadingTimer = SPARK_VSR15_SCADA_unloadingTimer+1
    Else
            SPARK_VSR15_SCADA_unloadingTimer = 0
    End If
   bit_longWhileUnloading = SPARK_VSR15_SCADA_Discharge_Max_Time&gt;0 And SPARK_VSR15_SCADA_unloadingTimer&gt;SPARK_VSR15_SCADA_Discharge_Max_Time

    If General_Spark_VSR15_PLCStateVariable = 0 Then
        Try
            bit_AlarmTemperature = SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR15_SCADA_CorkTemp_Alarm
        Catch
            Finally
        End Try
    End If

    If General_Spark_VSR15_PLCStateVariable = 0 Then
        Try
            If SPARK_VSR15_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR15_SCADA_CorkTemp_Max Then
                SPARK_VSR15_SCADA_MaxTemperatureTimer = SPARK_VSR15_SCADA_MaxTemperatureTimer+1
            Else
                    SPARK_VSR15_SCADA_MaxTemperatureTimer = 0
            End If
        Catch
            Finally
        End Try
    End If
   bit_longWhileMaxTemperature = SPARK_VSR15_SCADA_CorkTemp_Max_Time&gt;0 And SPARK_VSR15_SCADA_MaxTemperatureTimer&gt;SPARK_VSR15_SCADA_CorkTemp_Max_Time

   SPARK_VSR15_SCADA_abnormalTreatment = bit_longWhileUnloading Or bit_AlarmTemperature Or bit_longWhileMaxTemperature

'VSR16
    If SPARK_VSR16_Status = 3 Then
        SPARK_VSR16_SCADA_unloadingTimer = SPARK_VSR16_SCADA_unloadingTimer+1
    Else
            SPARK_VSR16_SCADA_unloadingTimer = 0
    End If
   bit_longWhileUnloading = SPARK_VSR16_SCADA_Discharge_Max_Time&gt;0 And SPARK_VSR16_SCADA_unloadingTimer&gt;SPARK_VSR16_SCADA_Discharge_Max_Time

    If General_Spark_VSR16_PLCStateVariable = 0 Then
        Try
            bit_AlarmTemperature = SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR16_SCADA_CorkTemp_Alarm
        Catch
            Finally
        End Try
    End If

    If General_Spark_VSR16_PLCStateVariable = 0 Then
        Try
            If SPARK_VSR16_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR16_SCADA_CorkTemp_Max Then
                SPARK_VSR16_SCADA_MaxTemperatureTimer = SPARK_VSR16_SCADA_MaxTemperatureTimer+1
            Else
                    SPARK_VSR16_SCADA_MaxTemperatureTimer = 0
            End If
        Catch
            Finally
        End Try
    End If
   bit_longWhileMaxTemperature = SPARK_VSR16_SCADA_CorkTemp_Max_Time&gt;0 And SPARK_VSR16_SCADA_MaxTemperatureTimer&gt;SPARK_VSR16_SCADA_CorkTemp_Max_Time

   SPARK_VSR16_SCADA_abnormalTreatment = bit_longWhileUnloading Or bit_AlarmTemperature Or bit_longWhileMaxTemperature

'VSR17
    If SPARK_VSR17_Status = 3 Then
        SPARK_VSR17_SCADA_unloadingTimer = SPARK_VSR17_SCADA_unloadingTimer+1
    Else
            SPARK_VSR17_SCADA_unloadingTimer = 0
    End If
   bit_longWhileUnloading = SPARK_VSR17_SCADA_Discharge_Max_Time&gt;0 And SPARK_VSR17_SCADA_unloadingTimer&gt;SPARK_VSR17_SCADA_Discharge_Max_Time

    If General_Spark_VSR17_PLCStateVariable = 0 Then
        Try
            bit_AlarmTemperature = SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR17_SCADA_CorkTemp_Alarm
        Catch
            Finally
        End Try
    End If

    If General_Spark_VSR17_PLCStateVariable = 0 Then
        Try
            If SPARK_VSR17_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR17_SCADA_CorkTemp_Max Then
                SPARK_VSR17_SCADA_MaxTemperatureTimer = SPARK_VSR17_SCADA_MaxTemperatureTimer+1
            Else
                    SPARK_VSR17_SCADA_MaxTemperatureTimer = 0
            End If
        Catch
            Finally
        End Try
    End If
   bit_longWhileMaxTemperature = SPARK_VSR17_SCADA_CorkTemp_Max_Time&gt;0 And SPARK_VSR17_SCADA_MaxTemperatureTimer&gt;SPARK_VSR17_SCADA_CorkTemp_Max_Time

   SPARK_VSR17_SCADA_abnormalTreatment = bit_longWhileUnloading Or bit_AlarmTemperature Or bit_longWhileMaxTemperature

'VSR18
    If SPARK_VSR18_Status = 3 Then
        SPARK_VSR18_SCADA_unloadingTimer = SPARK_VSR18_SCADA_unloadingTimer+1
    Else
            SPARK_VSR18_SCADA_unloadingTimer = 0
    End If
   bit_longWhileUnloading = SPARK_VSR18_SCADA_Discharge_Max_Time&gt;0 And SPARK_VSR18_SCADA_unloadingTimer&gt;SPARK_VSR18_SCADA_Discharge_Max_Time

    If General_Spark_VSR18_PLCStateVariable = 0 Then
        Try
            bit_AlarmTemperature = SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR18_SCADA_CorkTemp_Alarm
        Catch
            Finally
        End Try
    End If

    If General_Spark_VSR18_PLCStateVariable = 0 Then
        Try
            If SPARK_VSR18_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR18_SCADA_CorkTemp_Max Then
                SPARK_VSR18_SCADA_MaxTemperatureTimer = SPARK_VSR18_SCADA_MaxTemperatureTimer+1
            Else
                    SPARK_VSR18_SCADA_MaxTemperatureTimer = 0
            End If
        Catch
            Finally
        End Try
    End If
   bit_longWhileMaxTemperature = SPARK_VSR18_SCADA_CorkTemp_Max_Time&gt;0 And SPARK_VSR18_SCADA_MaxTemperatureTimer&gt;SPARK_VSR18_SCADA_CorkTemp_Max_Time

   SPARK_VSR18_SCADA_abnormalTreatment = bit_longWhileUnloading Or bit_AlarmTemperature Or bit_longWhileMaxTemperature

'VSR19
    If SPARK_VSR19_Status = 3 Then
        SPARK_VSR19_SCADA_unloadingTimer = SPARK_VSR19_SCADA_unloadingTimer+1
    Else
            SPARK_VSR19_SCADA_unloadingTimer = 0
    End If
   bit_longWhileUnloading = SPARK_VSR19_SCADA_Discharge_Max_Time&gt;0 And SPARK_VSR19_SCADA_unloadingTimer&gt;SPARK_VSR19_SCADA_Discharge_Max_Time

    If General_Spark_VSR19_PLCStateVariable = 0 Then
        Try
            bit_AlarmTemperature = SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR19_SCADA_CorkTemp_Alarm
        Catch
            Finally
        End Try
    End If

    If General_Spark_VSR19_PLCStateVariable = 0 Then
        Try
            If SPARK_VSR19_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR19_SCADA_CorkTemp_Max Then
                SPARK_VSR19_SCADA_MaxTemperatureTimer = SPARK_VSR19_SCADA_MaxTemperatureTimer+1
            Else
                    SPARK_VSR19_SCADA_MaxTemperatureTimer = 0
            End If
        Catch
            Finally
        End Try
    End If
   bit_longWhileMaxTemperature = SPARK_VSR19_SCADA_CorkTemp_Max_Time&gt;0 And SPARK_VSR19_SCADA_MaxTemperatureTimer&gt;SPARK_VSR19_SCADA_CorkTemp_Max_Time

   SPARK_VSR19_SCADA_abnormalTreatment = bit_longWhileUnloading Or bit_AlarmTemperature Or bit_longWhileMaxTemperature

'VSR20
    If SPARK_VSR20_Status = 3 Then
        SPARK_VSR20_SCADA_unloadingTimer = SPARK_VSR20_SCADA_unloadingTimer+1
    Else
            SPARK_VSR20_SCADA_unloadingTimer = 0
    End If
   bit_longWhileUnloading = SPARK_VSR20_SCADA_Discharge_Max_Time&gt;0 And SPARK_VSR20_SCADA_unloadingTimer&gt;SPARK_VSR20_SCADA_Discharge_Max_Time

    If General_Spark_VSR20_PLCStateVariable = 0 Then
        Try
            bit_AlarmTemperature = SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR20_SCADA_CorkTemp_Alarm
        Catch
            Finally
        End Try
    End If

    If General_Spark_VSR20_PLCStateVariable = 0 Then
        Try
            If SPARK_VSR20_PLC_KTP_Temperat_PV_Rolhas &gt; SPARK_VSR20_SCADA_CorkTemp_Max Then
                SPARK_VSR20_SCADA_MaxTemperatureTimer = SPARK_VSR20_SCADA_MaxTemperatureTimer+1
            Else
                    SPARK_VSR20_SCADA_MaxTemperatureTimer = 0
            End If
        Catch
            Finally
        End Try
    End If
   bit_longWhileMaxTemperature = SPARK_VSR20_SCADA_CorkTemp_Max_Time&gt;0 And SPARK_VSR20_SCADA_MaxTemperatureTimer&gt;SPARK_VSR20_SCADA_CorkTemp_Max_Time

   SPARK_VSR20_SCADA_abnormalTreatment = bit_longWhileUnloading Or bit_AlarmTemperature Or bit_longWhileMaxTemperature

End Sub
</sCode>
  <sessionName i:nil="true" />
  <slowSamplingInterval>5000</slowSamplingInterval>
  <stopCommandTimeout>2000</stopCommandTimeout>
  <threadPriority>Normal</threadPriority>
  <useAlwaysSecureConnections>false</useAlwaysSecureConnections>
  <writeTimeout>0</writeTimeout>
</ScriptDocument>